@startuml

title __APP's Class Diagram__\n

  package ch.web4b.myapplication {
    package ch.web4b.myapplication.data {
      package ch.web4b.myapplication.databinding {
        abstract class ActivityMain2Binding {
        }
      }
    }
  }
  

  package ch.web4b.myapplication {
    package ch.web4b.myapplication.data {
      package ch.web4b.myapplication.databinding {
        class ActivityMain2BindingImpl {
        }
      }
    }
  }
  

  package ch.web4b.myapplication {
    package ch.web4b.myapplication.data {
      package ch.web4b.myapplication.databinding {
        abstract class ActivityMainBinding {
        }
      }
    }
  }
  

  package ch.web4b.myapplication {
    package ch.web4b.myapplication.data {
      package ch.web4b.myapplication.databinding {
        class ActivityMainBindingImpl {
        }
      }
    }
  }
  

  package com.android.databinding.library.baseAdapters {
    class BR {
    }
  }
  

  package ch.web4b.myapplication {
    class BR {
    }
  }
  

  package ch.web4b.myapplication {
    class BuildConfig {
    }
  }
  

  package android.databinding {
    class DataBinderMapperImpl {
    }
  }
  

  package ch.web4b.myapplication {
    class DataBinderMapperImpl {
    }
  }
  

  package android.databinding {
    interface DataBindingComponent {
    }
  }
  

  package ch.web4b.myapplication {
    class DataBindingInfo {
    }
  }
  

  package ch.web4b.myapplication {
    package ch.web4b.myapplication.data {
      class DataHolder {
      }
    }
  }
  

  package ch.web4b.myapplication {
    class ExampleInstrumentedTest {
    }
  }
  

  package ch.web4b.myapplication {
    package ch.web4b.myapplication.dto.github {
      class Job {
      }
    }
  }
  

  package ch.web4b.myapplication {
    class Main2Activity {
    }
  }
  

  package ch.web4b.myapplication {
    class MainActivity {
    }
  }
  

  package ch.web4b.myapplication {
    package ch.web4b.myapplication.data {
      class Service {
      }
    }
  }
  

  ActivityMain2Binding -up-|> ViewDataBinding
  ActivityMain2Binding o-- Service : mService
  ActivityMain2BindingImpl -up-|> ActivityMain2Binding
  ActivityMainBinding -up-|> ViewDataBinding
  ActivityMainBinding o-- Service : mService
  ActivityMainBindingImpl -up-|> ActivityMainBinding
  DataBinderMapperImpl -up-|> MergedDataBinderMapper
  DataBinderMapperImpl -up-|> DataBinderMapper
  Main2Activity -up-|> AppCompatActivity
  Main2Activity o-- ActivityMain2Binding : binding
  Main2Activity o-- Main2Activity : main2Activity
  MainActivity -up-|> OnInitListener
  MainActivity -up-|> AppCompatActivity
  MainActivity o-- MainActivity : mainActivity
  MainActivity o-- ActivityMainBinding : binding
  MainActivity o-- DataHolder : holder
  Service -up-|> BaseObservable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
